missionNameSpace setVariable ["gearUniform",            "rhs_uniform_g3_mc", true];
missionNameSpace setVariable ["gearVest",               "UK3CB_V_MBAV_LIGHT_MULTI", true];
missionNameSpace setVariable ["gearBackpack",           "UK3CB_GAF_B_B_ASS_MULTICAM_02", true];
missionNameSpace setVariable ["gearHeadgear",           "rhsusf_mich_bare_norotos_arc_semi", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "TFAR_mr3000_multicam", true];
missionNameSpace setVariable ["gearNightvision",        "A3_GPNVG18_BLK_F", true];
missionNameSpace setVariable ["gearWeapon1Use",         "", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_mk18_bk", "rhs_mag_30Rnd_556x45_M855A1_PMAG", ["rhsusf_acc_compm4", "rhsusf_acc_wmx_bk", "rhsusf_acc_nt4_black", "rhsusf_acc_kac_grip"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_lmg_mk48", "hlc_100Rnd_762x51_M_M60E4", ["bwa3_optic_microt2", "rhsusf_acc_wmx_bk", "rhsusf_acc_harris_bipod", "rhsusf_acc_ardec_m240"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_mk18_m320", "rhs_mag_30Rnd_556x45_M855A1_PMAG", ["rhsusf_acc_compm4", "rhsusf_acc_wmx_bk", "rhsusf_acc_nt4_black"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["hlc_rifle_awmagnum", "hlc_5rnd_300WM_AP_AWM", ["optic_nvs"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
