missionNameSpace setVariable ["gearUniform",            "PB_CADPATMT_GoraG", true];
missionNameSpace setVariable ["gearVest",               "PB_CADPATMT_Carrier_Rig", true];
missionNameSpace setVariable ["gearBackpack",           "PB_EAGLE_CADPATMT", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_CADPATMT_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_CADPATMT", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m72a7", true];
missionNameSpace setVariable ["gearWeaponMain",         ["PB_C7", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red", ["rhsusf_acc_ELCAN"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["PB_C9", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["PB_C7M203", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red", ["rhsusf_acc_ELCAN"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_sr25_d", "rhsusf_20Rnd_762x51_SR25_m62_mag", ["ptv_PMII_des_sunshade", "rhsusf_acc_harris_bipod","rhsusf_acc_anpeq15A","rhsusf_acc_SR25S_d"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_maaws", "rhs_mag_maaws_HEAT", ["rhs_optic_maaws"]], true];
