missionNameSpace setVariable ["gearUniform",            "Uniform_Full_CADPAT", true];
missionNameSpace setVariable ["gearVest",               "vest_lite_CADPAT", true];
missionNameSpace setVariable ["gearBackpack",           "CADPAT_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_lwh_CADPAT", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_CADPAT_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["UK3CB_BAF_L119A1", "UK3CB_BAF_556_30Rnd_T", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["UK3CB_BAF_L119A1_UKUGL", "UK3CB_BAF_556_30Rnd_T", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15_bk"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["hlc_rifle_awmagnum", "hlc_5rnd_300WM_T_AWM", ["RKSL_optic_PMII_312"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
