missionNameSpace setVariable ["gearUniform",            "Uniform_Full_ERDLVZ", true];
missionNameSpace setVariable ["gearVest",               "vest_spc_rifleman_ERDLVZ", true];
missionNameSpace setVariable ["gearBackpack",           "ERDLVZ_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_lwh_ERDLVZ", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_tropentarn_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["QIN_CZ_BREN2_556_11", "30Rnd_556x45_Stanag_red", ["rhsusf_acc_ACOG"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["QIN_CZ_BREN2_556_11_GL", "30Rnd_556x45_Stanag_red", ["rhsusf_acc_ACOG"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_svds_npz", "rhs_10Rnd_762x54mmR_7N1", ["optic_AMS"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
