missionNameSpace setVariable ["gearUniform",            "PB_VZ95D_ACU", true];
missionNameSpace setVariable ["gearVest",               "PB_VZ95W_Modular_Lite", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_GREEN", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_VZ95D_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_GREEN", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_Rpg75", true];
missionNameSpace setVariable ["gearWeaponMain",         ["PB_QIN_CZ_BREN2_556_14", "PB_qin_30Rnd_556x45_Stanag_Tracer_Red", ["rhsusf_acc_compm4"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["PB_MINIMI_762", "PB_200Rnd_762x51_M62", [""]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["PB_QIN_CZ_BREN2_556_14_GL", "PB_qin_30Rnd_556x45_Stanag_Tracer_Red", ["rhsusf_acc_compm4"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["PB_FIN_TRG22", "rhs_5Rnd_338lapua_t5000", ["rhsusf_acc_premier_low","rhsusf_acc_harris_swivel"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_rpg7", "rhs_rpg7_PG7VL_mag", [""]], true];
