missionNameSpace setVariable ["gearUniform",            "rhsgref_uniform_3color_desert", true];
missionNameSpace setVariable ["gearVest",               "UK3CB_ANP_B_V_GA_HEAVY_TAN", true];
missionNameSpace setVariable ["gearBackpack",           "B_Kitbag_cbr", true];
missionNameSpace setVariable ["gearHeadgear",           "rhsgref_helmet_pasgt_3color_desert", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "TFAR_rt1523g_sage", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_ak104", "rhs_30Rnd_762x39mm_polymer_tracer", ["rhs_acc_pkas"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_lmg_M60E4", "hlc_100Rnd_762x51_M_M60E4", ["optic_aco"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_ak103_gp25", "rhs_30Rnd_762x39mm_polymer_tracer", ["rhs_acc_pkas"], "hlc_VOG25_AK"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_m40a5_d", "rhsusf_10Rnd_762x51_m62_Mag", ["optic_dms"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_rpg7", "rhs_rpg7_PG7VL_mag", [""]], true];
