missionNameSpace setVariable ["gearUniform",            "Uniform_Full_DCCE", true];
missionNameSpace setVariable ["gearVest",               "vest_lite_DCCE", true];
missionNameSpace setVariable ["gearBackpack",           "DCCE_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_lwh_DCCE", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_DCCE_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["bg21_famas_FS_blk", "25Rnd_556x45_famas_tr", ["rhsusf_acc_ACOG", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m240B", "rhsusf_100Rnd_762x51_m62_tracer", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_416D165_gl", "hlc_30rnd_556x45_t", ["rhsusf_acc_ACOG", "rhsusf_acc_anpeq15_bk"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["arifle_SPAR_03_blk_F", "ACE_20Rnd_762x51_Mag_Tracer", ["optic_AMS"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
