missionNameSpace setVariable ["gearUniform",            "PB_CCE_U", true];
missionNameSpace setVariable ["gearVest",               "PB_TAN_Carrier_Lite", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_CCE", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_CCE_H_N_A", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_CCE", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_hk416d145", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["ptv_compm5", "rhsusf_acc_grip3"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_minimi_para_railed", "rhsusf_200Rnd_556x45_M855_soft_pouch", ["ptv_specterdr6"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_hk416d145_m320", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["ptv_compm5", "rhsusf_acc_grip3"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["hlc_WP_SSR", "rhs_mag_20Rnd_SCAR_762x51_m62_tracer_bk", ["ptv_shortdot_dcc_wdl","rhs_acc_harris_swivel","HLC_Panel_Side_MagpulXT_Desert"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_O_vorona_green_F", "Vorona_HEAT", [""]], true];
