missionNameSpace setVariable ["gearUniform",            "Uniform_Full_TROPENTARN", true];
missionNameSpace setVariable ["gearVest",               "vest_spc_rifleman_TROPENTARN", true];
missionNameSpace setVariable ["gearBackpack",           "TROPENTARN_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_lwh_TROPENTARN", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_tropentarn_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["hlc_rifle_G36A1", "hlc_30rnd_556x45_Tracers_G36", ["HLC_Optic_G36Export35x2d"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_lmg_MG3", "hlc_100Rnd_762x51_T_MG3", [""]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_G36A1AG36", "hlc_30rnd_556x45_Tracers_G36", ["HLC_Optic_G36Export35x2d"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["arifle_SPAR_03_blk_F", "ACE_20Rnd_762x51_Mag_Tracer", ["optic_AMS"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
