missionNameSpace setVariable ["gearUniform",            "PB_TROP_ACU", true];
missionNameSpace setVariable ["gearVest",               "PB_TROP_Carrier_Rig", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_TROP", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_TROP_FAST_C_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_TROp", true];
missionNameSpace setVariable ["gearNightvision",        "UK3CB_ANPVS7", true];
missionNameSpace setVariable ["gearWeapon1Use",         "", true];
missionNameSpace setVariable ["gearWeaponMain",         ["PB_G36", "PB_M856A1_G36", ["rhsusf_acc_su230_c","ptv_LLM_des"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["PB_MG5", "hlc_100Rnd_762x51_T_MG3", ["rhsusf_acc_su230_c","HLC_bipod_UTGshooters"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["PB_G36_GL", "PB_M856A1_G36", ["rhsusf_acc_su230_c","ptv_LLM_des"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["BWA3_G28", "BWA3_20Rnd_762x51_G28_Tracer", ["BWA3_optic_PMII_DMR_MicroT1_front","muzzlesnds_B_arid_F","ptv1a2"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["PB_PZF3", "PB_DM12_HEAT_F", [""]], true];
