missionNameSpace setVariable ["gearUniform",            "PB_GRELIZ_GoraG", true];
missionNameSpace setVariable ["gearVest",               "PB_GREEN_Carrier_Lite", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_GRELIZ", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_GRELIZ_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_GRELIZ", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m72a7", true];
missionNameSpace setVariable ["gearWeaponMain",         ["PB_G3", "20Rnd_762x51_Mag", [""]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_lmg_minimi", "rhsusf_200Rnd_556x45_M855_soft_pouch", [""]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_g3ka4_GL", "ACE_20Rnd_762x51_Tracer", [""], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["hlc_rifle_g3a3", "ACE_20Rnd_762x51_Tracer", ["hlc_optic_STANAGZF_G3"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_maaws", "rhs_mag_maaws_HEAT", [""]], true];
