missionNameSpace setVariable ["gearUniform",            "PB_IDF_GoraG", true];
missionNameSpace setVariable ["gearVest",               "PB_Green_M12_VEST", true];
missionNameSpace setVariable ["gearBackpack",           "PB_ASSAULT_MED_GREEN", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_IDF_mich_bare", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523_BIG_GREEN", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m72a7", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_m4_carryhandle", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red", ["rhsusf_acc_eotech_552"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["ptv_ng5_b", "ptv_150Rnd_556x45_Negev_Tracer_Red", ["rhsusf_acc_eotech_552"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_m4_carryhandle_m203", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull_Tracer_Red", ["rhsusf_acc_eotech_552"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_m24sws", "rhsusf_5Rnd_762x51_m62_Mag", ["rhsusf_acc_nxs_3515x50f1_h58_sun","rhsusf_acc_harris_swivel"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["BWA3_RGW90_Loaded", "", [""]], true];
