missionNameSpace setVariable ["gearUniform",            "PB_LATPAT_ACU", true];
missionNameSpace setVariable ["gearVest",               "PB_LATPAT_TST", true];
missionNameSpace setVariable ["gearBackpack",           "PB_COMBAT_LATPAT", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_LATPAT_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_LATPAT", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["PB_G36", "PB_M856A1_G36", ["rhsusf_acc_compm4"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_minimi_para_railed", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ACOG"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["PB_G36_GL", "PB_M856A1_G36", ["rhsusf_acc_compm4"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["UK3CB_BAF_L115A3", "UK3CB_BAF_338_5Rnd_TRACER", ["rhsusf_acc_nxs_3515x50f1_h58_sun"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_maaws", "rhs_mag_maaws_HEAT", [""]], true];
