missionNameSpace setVariable ["gearUniform",            "PB_M98_ACU", true];
missionNameSpace setVariable ["gearVest",               "rhsusf_mbav_rifleman", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_M98", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_M98_FAST", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_M98", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "uk3cb_m72a1_law_loaded", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_hk416d145", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["rhsusf_acc_compm4", "rhsusf_acc_kac_grip"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_minimi_para_railed", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_hk416d145_M320", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["rhsusf_acc_compm4"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["arifle_SPAR_03_blk_F", "ACE_20Rnd_762x51_Mag_Tracer", ["ptv_shortdot_cc", "rhs_acc_harris_swivel"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_maaws", "rhs_mag_maaws_HEAT", [""]], true];