missionNameSpace setVariable ["gearUniform",            "Uniform_Full_CIRCA", true];
missionNameSpace setVariable ["gearVest",               "vest_spc_rifleman_CIRCA", true];
missionNameSpace setVariable ["gearBackpack",           "CIRCA_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_lwh_CIRCA", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_CIRCA_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["hlc_rifle_416D165", "hlc_30rnd_556x45_t", ["rhsusf_acc_ACOG3_USMC", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_416D165_gl", "hlc_30rnd_556x45_t", ["rhsusf_acc_ACOG3_USMC", "rhsusf_acc_anpeq15a"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["arifle_SPAR_03_blk_F", "ACE_20Rnd_762x51_Mag_Tracer", ["optic_AMS", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];