missionNameSpace setVariable ["gearUniform",            "UK3CB_LSM_B_U_CombatUniform_09", true];
missionNameSpace setVariable ["gearVest",               "vest_spc_OLIVE", true];
missionNameSpace setVariable ["gearBackpack",           "OLIVE_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "H_PASGT_basic_black_F", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_olive_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "NVGoggles_OPFOR", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["hlc_rifle_ACR_SBR_black", "hlc_30rnd_556x45_t", ["rhsusf_acc_g33_xps3", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_ACR_GL_SBR_black", "hlc_30rnd_556x45_t", ["rhsusf_acc_g33_xps3", "rhsusf_acc_anpeq15a"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_m14ebrri", "rhsusf_20Rnd_762x51_m62_Mag", ["optic_AMS", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];