missionNameSpace setVariable ["gearUniform",            "usm_bdu_bnu_ubntgrstp", true];
missionNameSpace setVariable ["gearVest",               "V_PlateCarrier1_blk", true];
missionNameSpace setVariable ["gearBackpack",           "B_TacticalPack_blk", true];
missionNameSpace setVariable ["gearHeadgear",           "usm_helmet_pasgt_ce_gry", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "TFAR_rt1523g_black", true];
missionNameSpace setVariable ["gearNightvision",        "NVGoggles_OPFOR", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["hlc_rifle_ak12", "hlc_30Rnd_545x39_t_ak_Black", ["rhsusf_acc_g33_xps3", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_rifle_RPK12", "hlc_60Rnd_545x39_t_rpk", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_ak12GL", "hlc_30Rnd_545x39_t_ak_Black", ["rhsusf_acc_g33_xps3", "rhsusf_acc_anpeq15a"], "hlc_VOG25_AK"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_svds_npz", "rhs_10Rnd_762x54mmR_7N1", ["optic_AMS"], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["RPG32_Olive", "RPG32_F", [""]], true];