missionNameSpace setVariable ["gearUniform",            "rhs_uniform_msv_emr", true];
missionNameSpace setVariable ["gearVest",               "rhs_6b23_digi_6sh92", true];
missionNameSpace setVariable ["gearBackpack",           "OLIVE_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "rhs_6b27m_digi_ess_bala", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_olive_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhs_1PN138", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_rpg26", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_ak74m", "rhs_30Rnd_545x39_AK_plum_green", ["rhs_acc_dtk", "rhs_acc_perst1ik"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_pkp", "rhs_100Rnd_762x54mmR_green", [""]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_ak74m_gp25", "rhs_30Rnd_545x39_AK_plum_green", ["rhs_acc_dtk", "rhs_acc_perst1ik"], "rhs_VOG25"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_svdp", "ACE_10Rnd_762x54_Tracer_mag", ["rhs_acc_pso1m21"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["RPG32_Olive", "RPG32_F", [""]], true];