missionNameSpace setVariable ["gearUniform",            "rhs_uniform_gorka_r_g_gloves", true];
missionNameSpace setVariable ["gearVest",               "rhs_6b45_rifleman", true];
missionNameSpace setVariable ["gearBackpack",           "rhs_rk_sht_30_olive", true];
missionNameSpace setVariable ["gearHeadgear",           "rhs_altyn_novisor_ess", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_fadak", true];
missionNameSpace setVariable ["gearBackpackLeader",     "UK3CB_TKA_O_B_RIF_Khk_Radio", true];
missionNameSpace setVariable ["gearNightvision",        "", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_rpg26", true];
missionNameSpace setVariable ["gearWeaponMain",         ["hlc_rifle_ak12", "rhs_mag_30Rnd_545x39_7N22_AK", ["rhsusf_acc_1p87", "rhsusf_acc_perst3", "rhsusf_acc_ak5", "rhsusf_acc_grip_rk2"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["hlc_rifle_RPK12", "hlc_60Rnd_545x39_t_rpk", ["rhsusf_acc_1p87", "rhsusf_acc_perst3", "rhs_acc_harris_swivel", "rhs_acc_dtk2"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["hlc_rifle_ak12GL", "rhs_mag_30Rnd_545x39_7N22_AK", ["rhsusf_acc_1p87", "rhsusf_acc_perst3", "rhsusf_acc_ak5"], "hlc_VOG25_AK"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["rhs_weap_svds_npz", "rhs_10Rnd_762x45mmR_7N14", ["rhs_acc_dh520x56"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["rhs_weap_rpg7", "rhs_rpg7_PG7VL_mag", ["rhs_acc_pgo7v3"]], true];
