missionNameSpace setVariable ["gearUniform",            "PB_M90_GoraG", true];
missionNameSpace setVariable ["gearVest",               "PB_M90_Modular_Lite", true];
missionNameSpace setVariable ["gearBackpack",           "PB_EAGLE_M90", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_M90_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_M90", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["rhs_weap_hk416d10", "rhs_mag_30Rnd_556x45_M855_PMAG", ["rhsusf_acc_compm4", "rhsusf_acc_kac_grip", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_minimi_para_railed", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_compm4", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["rhs_weap_hk416d10_m320", "rhs_mag_30Rnd_556x45_M855_PMAG", ["rhsusf_acc_compm4", "rhsusf_acc_anpeq15a"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["arifle_SPAR_03_blk_F", "ACE_20Rnd_762x51_Mag_Tracer", ["ptv_shortdot_dcc", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];