missionNameSpace setVariable ["gearUniform",            "PB_MTP_ACU", true];
missionNameSpace setVariable ["gearVest",               "PB_MTP_Modular_Lite", true];
missionNameSpace setVariable ["gearBackpack",           "PB_Kitbag_MTP", true];
missionNameSpace setVariable ["gearHeadgear",           "PB_MTP_H", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "PB_RT1523BIG_MTP", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["UK3CB_BAF_L85A3", "UK3CB_BAF_556_30Rnd_T", ["RKSL_optic_LDS", "UK3CB_BAF_LLM_IR_Tan","UK3CB_underbarrel_acc_grippod"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["UK3CB_BAF_L7A2", "UK3CB_BAF_762_100Rnd_T", []], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["UK3CB_BAF_L85A3_UGL", "UK3CB_BAF_556_30Rnd_T", ["RKSL_optic_LDS", "UK3CB_BAF_LLM_IR_Tan"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["UK3CB_BAF_L129A1", "UK3CB_BAF_762_L42A1_20Rnd_T", ["UK3CB_BAF_TA648","UK3CB_underbarrel_acc_fgrip_bipod"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
