missionNameSpace setVariable ["gearUniform",            "Uniform_Full_MTP", true];
missionNameSpace setVariable ["gearVest",               "vest_spc_rifleman_MTP", true];
missionNameSpace setVariable ["gearBackpack",           "MTP_Kitbag", true];
missionNameSpace setVariable ["gearHeadgear",           "helmet_plain_MTP", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_MTP_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["UK3CB_BAF_L85A3", "UK3CB_BAF_556_30Rnd_T", ["rhsusf_acc_ACOG", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ACOG", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["UK3CB_BAF_L85A3_UGL", "UK3CB_BAF_556_30Rnd_T", ["rhsusf_acc_ACOG", "rhsusf_acc_anpeq15_bk"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["UK3CB_BAF_L129A1", "UK3CB_BAF_762_L42A1_20Rnd_T", ["RKSL_optic_PMII_312"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
