missionNameSpace setVariable ["gearUniform",            "rhs_uniform_FROG01_d", true];
missionNameSpace setVariable ["gearVest",               "rhsusf_spc_rifleman", true];
missionNameSpace setVariable ["gearBackpack",           "B_Kitbag_cbr", true];
missionNameSpace setVariable ["gearHeadgear",           "rhsusf_lwh_helmet_marpatd", true];
missionNameSpace setVariable ["gearRadio",              "TFAR_anprc152", true];
missionNameSpace setVariable ["gearBackpackLeader",     "unv_MARPAT_D_big_rt1523g", true];
missionNameSpace setVariable ["gearNightvision",        "rhsusf_ANPVS_14", true];
missionNameSpace setVariable ["gearWeapon1Use",         "rhs_weap_m136", true];
missionNameSpace setVariable ["gearWeaponMain",         ["ArmaReTex_M16A3_Carryhandle", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["rhsusf_acc_ACOG_USMC_USMC", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponAR",           ["rhs_weap_m249_pip_L", "rhsusf_200Rnd_556x45_mixed_box", ["rhsusf_acc_ELCAN", "rhsusf_acc_anpeq15a"]], true];
missionNameSpace setVariable ["gearWeaponGrenadier",    ["ArmaReTex_M16A3_M203", "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red", ["rhsusf_acc_ACOG_USMC", "rhsusf_acc_anpeq15a"], "rhs_mag_M441_HE"], true];
missionNameSpace setVariable ["gearWeaponMarksman",     ["hlc_rifle_M14dmr_Rail", "hlc_20Rnd_762x51_T_M14", ["optic_AMS", "rhsusf_acc_anpeq15_bk"]], true];
missionNameSpace setVariable ["gearWeaponLauncher",     ["launch_MRAWS_olive_rail_F", "MRAWS_HEAT_F", [""]], true];
